### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by Palle47** [maxie-max/TindHancer.com#1]
Hi. Recorded the issue I have as mentioned on the youtube thread. I clicked it too many times and there are no pictures loading due to this. I have the same problem though as I can see pictures in the beginning and when I finally get the page to load, it goes blank..
https://www.awesomescreenshot.com/video/50857?key=154d597bf4b907364fe6a52ff379cb1f

**Comment by Palle47** [comment]
I can make another recording later to be more illustrative when the rate issue is not present

**Comment by Palle47** [comment]
https://www.awesomescreenshot.com/video/52392?key=82c5a461d67fef8705faecc9f84df33c

**Comment by Palle47** [comment]
Video above demonstrates the problem well.// Hope you can solve this.

**Comment by maxie-max** [comment]
> Video above demonstrates the problem well.// Hope you can solve this.

Tnx @Palle47 for submitting an issue.

I can't seem reproduce it on Mac and Linux on Firefox, Chrome/Chromium, Safari browsers

Any chance you could provide me with the following:

- Operating System (looks like Windows 8)
- Browser Version
- What actions you took prior seeing the page with an error
- Would be awesome to get a screen shot with the error log in the browser dev tools console as well, like so:
![image](https://user-images.githubusercontent.com/4652341/80808191-46bc9580-8bbf-11ea-803e-439503cdcdbb.png)

Unfortunately the screen record you provided doesn't help me much.

Could you try to clear cache and local storage like so 
![image](https://user-images.githubusercontent.com/4652341/80808520-027dc500-8bc0-11ea-9aa1-c666e177fd82.png)

**Comment by Palle47** [comment]
Hi there,
Windows 10. Use Chrome default and firefox.
![Skärmklipp](https://user-images.githubusercontent.com/64617178/80842866-fc5d0800-8c02-11ea-9934-497ac970f951.JPG)
![Skärmklipp2](https://user-images.githubusercontent.com/64617178/80842878-0252e900-8c03-11ea-97a5-14aaede31de9.JPG)

**Comment by Palle47** [comment]
Also, I cleared cache and local storage. I tried this ob 2 different computers with chrome and firefox. It doesnt work for me.

**Comment by maxie-max** [comment]
I fixed the bug related to the console log error you provided which should not appear there in the first place. 
Could you try to open the app in incognito mode on chrome browser? 
Meaning to run the app purely without any single browser extension. Could be that one of your extensions interfere with the app somehow. Just my theory...
I've tested it on windows 8/chrome in virtual box just now (still can't reproduce to what you are experiencing)
Once I get a chance to get my hands on Windows 10 will test there it as well.

**Comment by Palle47** [comment]
No difference in incognito mode I´m afraid. See the screenshot..
I have also tried it on an IPad and on an android phone. The page loads and disappears..
![Skärmklipp](https://user-images.githubusercontent.com/64617178/80870098-91640d80-8ca4-11ea-94e2-937e41784c9e.PNG)

**Comment by maxie-max** [comment]
@Palle47 Do you by any chance see anything odd when using the web/browser based version of Tinder?

**Comment by Palle47** [comment]
No. There was this trick to you could do and unblur the photos by the inspection menu. It doesn't work anymore. Your page actually unblurs and I can see a few pics before it goes blank again..

Skickat från Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by maxie-max** [comment]
It looks like the issue you have is particularly related to your profile.
I'm gonna monitor Tindhancer for a similar bug, but so far I have not been able to reproduce it. Having tested with several profiles, various devices, browsers(Safari, Firefox, Chrome) and OS (Windows 8, Mac OS, Android, iOS)

**Comment by Palle47** [comment]
I’ve tried everything I can think of. The other night,refreshing the page a few times, I was actually able to view it for a minute. Great fun!. Then it went blank again...


Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: maxie-max <notifications@github.com>
Skickat: Thursday, May 7, 2020 1:53:01 PM
Till: maxie-max/TindHancer.com <TindHancer.com@noreply.github.com>
Kopia: Palle47 <clivehasse@hotmail.com>; Mention <mention@noreply.github.com>
Ämne: Re: [maxie-max/TindHancer.com] Not loading (#1)


It looks like the issue you have is particularly related to your profile.
I'm gonna monitor Tindhancer for a similar bug, but so far I have not been able to reproduce it. Having tested with several profiles, various devices, browsers(Safari, Firefox, Chrome) and OS (Windows 8, Mac OS, Android, iOS)

**Comment by Palle47** [comment]
Works now!! Great!

**Comment by Palle47** [comment]
But it lasted only for a day...:(

**Comment by maxie-max** [comment]
It could relate to this issue https://github.com/fbessez/Tinder/issues/76

**Comment by maxie-max** [comment]
It's fixed

**Comment by Palle47** [comment]
It works!. Great!. Thanks
